package vn.restauranttycoon.economy;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class EconomyRepositoryTest {
    private DataSource dataSource;
    private EconomyRepository repository;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource database = new JdbcDataSource();
        database.setURL("jdbc:h2:mem:" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        dataSource = database;
        createSchema();
        repository = new EconomyRepository(dataSource);
    }

    @Test
    void returnsTheOriginalResultForAnIdenticalRetry() throws SQLException {
        UUID accountId = UUID.randomUUID();
        OperationKey key = OperationKey.create();

        LedgerResult first = repository.apply(accountId, key, 100, "TEST_GRANT");
        LedgerResult retry = repository.apply(accountId, key, 100, "TEST_GRANT");

        assertFalse(first.duplicate());
        assertTrue(retry.duplicate());
        assertEquals(first.balance(), retry.balance());
        assertEquals(first.revision(), retry.revision());
        assertEquals(1, ledgerCount());
    }

    @Test
    void rejectsReuseOfAnOperationKeyForDifferentInputs() throws SQLException {
        UUID accountId = UUID.randomUUID();
        OperationKey key = OperationKey.create();
        repository.apply(accountId, key, 100, "TEST_GRANT");

        assertThrows(OperationKeyConflictException.class,
                () -> repository.apply(accountId, key, 101, "TEST_GRANT"));
        assertThrows(OperationKeyConflictException.class,
                () -> repository.apply(UUID.randomUUID(), key, 100, "TEST_GRANT"));
        assertEquals(1, ledgerCount());
    }

    @Test
    void rollsBackAnInsufficientDebit() throws SQLException {
        UUID accountId = UUID.randomUUID();
        repository.apply(accountId, OperationKey.create(), 50, "TEST_GRANT");

        assertThrows(InsufficientFundsException.class,
                () -> repository.apply(accountId, OperationKey.create(), -51, "TEST_DEBIT"));
        assertEquals(new CurrencyAmount(50), repository.balance(accountId));
        assertEquals(1, ledgerCount());
    }

    @Test
    void serializesConcurrentRetriesToOneMutation() throws Exception {
        UUID accountId = UUID.randomUUID();
        OperationKey key = OperationKey.create();
        ExecutorService executor = Executors.newFixedThreadPool(8);
        try {
            CompletableFuture<?>[] attempts = new CompletableFuture<?>[100];
            for (int index = 0; index < attempts.length; index++) {
                attempts[index] = CompletableFuture.supplyAsync(() -> {
                    try {
                        return repository.apply(accountId, key, 25, "TEST_GRANT");
                    } catch (SQLException exception) {
                        throw new IllegalStateException(exception);
                    }
                }, executor);
            }
            CompletableFuture.allOf(attempts).get(10, TimeUnit.SECONDS);
        } finally {
            executor.shutdownNow();
        }

        assertEquals(new CurrencyAmount(25), repository.balance(accountId));
        assertEquals(1, ledgerCount());
    }

    private void createSchema() throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE economy_accounts (
                        account_id UUID PRIMARY KEY,
                        balance BIGINT NOT NULL DEFAULT 0 CHECK (balance >= 0),
                        revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE economy_ledger (
                        ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        operation_id UUID NOT NULL UNIQUE,
                        account_id UUID NOT NULL REFERENCES economy_accounts(account_id),
                        delta BIGINT NOT NULL CHECK (delta <> 0),
                        balance_after BIGINT NOT NULL CHECK (balance_after >= 0),
                        account_revision BIGINT NOT NULL CHECK (account_revision > 0),
                        reason VARCHAR(64) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
        }
    }

    private int ledgerCount() throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery("SELECT COUNT(*) FROM economy_ledger")) {
            result.next();
            return result.getInt(1);
        }
    }
}
